[rules]
case_default = true
default_nettype_none = true
function_same_as_system_function = true
genvar_declaration_in_loop = true
interface_port_with_modport = true
loop_variable_declaration = true
non_ansi_module = true
uppercamelcase_interface = true
uppercamelcase_module = true
uppercamelcase_package = true
